name: publish_mod

on:
  repository_dispatch:
    types: [publish_mod]
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [ 3.10.8 ]

    steps:
      - uses: actions/checkout@v3

      - name: Get steamcmd
        run: |
          curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip --output steamcmd.zip
          Expand-Archive -Path steamcmd.zip
      - name: Set credentials
        run: |
          python download_credentials.py
          dir
          cd steamcmd
          dir
          cd config
          dir
        env:
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

      - name: uploading steam workshop
        run: |
          cd steamcmd
          dir
          steamcmd.exe +quit
        env:
          STEAM_LOGIN_NAME: ${{ secrets.STEAM_LOGIN_NAME }}
          STEAM_LOGIN_PASSWORD: ${{ secrets.STEAM_LOGIN_PASSWORD }}
        shell: cmd
        continue-on-error: true
